Adding tapenade to configure and make

diff --git a/tools/makeAD b/tools/makeAD
--- a/tools/makeAD
+++ b/tools/makeAD
@@ -2,6 +2,19 @@
 
 path_to_script=$(dirname $0)
 #cd package/src
+
+if test -z "$1"
+then
+	TAPENADE="tapenade"
+else
+	TAPENADE="$1"
+fi
+if ! command -v "$TAPENADE"
+then
+	echo "Tapenade not found ('$TAPENADE')" >&2
+	exit -1
+fi
+
 . ADset.sh
 rm Dynamics_tmp.c Dynamics_b.c* ADpre_.h types_b.h tmp 2>/dev/null
 echo "#define CudaDeviceFunction" > Dynamics_tmp.c
@@ -16,11 +29,11 @@ cat Dynamics.c | sed 's/pow(\([^,]*\),3)/((\1)*(\1)*(\1))/g' >> Dynamics_tmp.c
 echo Variables for differentiation: $VARIABLES
 echo Additional variables for differentiation: $SETTINGS
 echo tapenade -html -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o DynamicsS -vars "$VARIABLES $SETTINGS" -outvars "$VARIABLES $SETTINGS"
-tapenade -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o DynamicsS -vars "$VARIABLES $SETTINGS" -outvars "$VARIABLES $SETTINGS"
+$TAPENADE -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o DynamicsS -vars "$VARIABLES $SETTINGS" -outvars "$VARIABLES $SETTINGS"
 echo "#define CONST_SETTINGS" > ADpre_.h
 cat ADpre.h >> ADpre_.h
 echo tapenade -html -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o DynamicsS -vars "$VARIABLES $SETTINGS" -outvars "$VARIABLES $SETTINGS"
-tapenade -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o Dynamics -vars "$VARIABLES" -outvars "$VARIABLES"
+$TAPENADE -msglevel 12 -b Dynamics_tmp.c -root $MAIN_FUN -o Dynamics -vars "$VARIABLES" -outvars "$VARIABLES"
 for f in Dynamics_b.c DynamicsS_b.c
 do
 	test -f $f || { echo "Tapenade failed"; exit -1; }
